swapObjects :caught logic error as expected
caught logic error as expected
old dict: 2
swapped array: /Array
new dict: 2
swapped array: /Array
array and dictionary contents are correct
test 14 done
